### ISSUE TITLE
Update for "kue": "~0.9.3"

### ISSUE THREAD

**Issue by han4wluc** [saintmac/unique-kue#3]
Hello,
I'd like to submit a pull request for the following:

#### Update the kue version from "kue": "~0.6.2" to "kue": "~0.9.3"
All tests still pass. But there is this message: 
>  promote method is deprecated, you don't need to call this anymore. You can safely remove it from your     code now.

So I'd like to remove the promote function.

#### Change the how to use documentation
I spent some time to figure out what I was doing wrong. It turns out I just needed to change the order of execution.

**This does NOT work**
kue = require('kue');
unique_kue = require('unique-kue');
unique_kue.setup(kue);
jobs = kue.createQueue();

**This works**
kue = require('kue');
unique_kue = require('unique-kue');
jobs = kue.createQueue();
unique_kue.setup(kue);

**Comment by saintmac** [comment]
Hi @han4wluc,
I'm sorry I missed your issue and pull request over the summer.
However I did find the need to upgrade to kue 0.9.x last month, so I upgraded this module to be compatible with it.
Feel free to submit a pull request to improve the documentation.
Thanks!
